global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Net;
global using System.Runtime.Serialization;
global using System.Threading.Tasks;
global using ErrorOr;
global using IndicatorsApi.Domain.Exceptions;
global using IndicatorsApi.Domain.Repositories;
